from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url

from app.views import *
from users.views import *

from project.routers import HybridRouter

# We use a single global DRF Router that routes views from all apps in project
router = HybridRouter()

# app views and viewsets
# router.register(r'tool', ToolViewSet, r"tool")
# router.register(r'author', AuthorViewSet, r"author")
# router.register(r'book', BookViewSet, r"book")
router.register(r'houses', HouseViewSet, r"houses")
router.register(r'user', UserViewSet, r"user")
router.register(r'badwords', BadwordView, r'badwords')
router.register(r'ManualCheck', ManualCheckView, r'ManualCheck')
router.register(r'ManualCheckPass', ManualCheckPassView, r'ManualCheckPass')
router.register(r'ManualCheckReject', ManualCheckRejectView, r'ManualCheckReject')
router.register(r'ShowHouseDetail', ShowHouseDetailView, r'ShowHouseDetail')
router.register(r'users', UserInteraction, r'users')
router.add_api_view(r'auth', url(r'^auth/$', ObtainAuthToken.as_view(), name=r"auth"))

urlpatterns = [
                  # default django admin interface (currently unused)
                  # url(r'^admin/', include(admin.site.urls)),

                  # root view of our REST api, generated by Django REST Framework's router
                  url(r'^api/', include(router.urls, namespace='api')),

                  # index page should be served by django to set cookies, headers etc.
                  url(r'^$', index_view, {}, name='index'),
                  url(r'personal_page', personal_page_view, {}, name='personal_page'),
                  url(r'add_release', add_release_view, {}, name='add_release'),
                  url(r'housedetail', house_detail_view, {}, name='housedetail'),
                  url(r'manualcheck', manual_check_view, {}, name='manualcheck'),
                  url(r'registration', user_register_view, {}, name='registration'),
                  url(r'login', user_login_view, {}, name='login'),
                  url(r'logout', user_logout_view, {}, r'logout')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# let django built-in server serve static and media content
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
